// Package Openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Data defines model for Data.
type Data struct {
	AX   *int     `json:"aX,omitempty"`
	AY   *int     `json:"aY,omitempty"`
	AZ   *int     `json:"aZ,omitempty"`
	GX   *int     `json:"gX,omitempty"`
	GY   *int     `json:"gY,omitempty"`
	GZ   *int     `json:"gZ,omitempty"`
	Temp *float32 `json:"temp,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

// SaveDataJSONBody defines parameters for SaveData.
type SaveDataJSONBody Data

// SaveDataRequestBody defines body for SaveData for application/json ContentType.
type SaveDataJSONRequestBody SaveDataJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A callback for modifying requests which are generated before sending over
	// the network.
	RequestEditor RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = http.DefaultClient
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditor = fn
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SaveData request  with any body
	SaveDataWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error)

	SaveData(ctx context.Context, body SaveDataJSONRequestBody) (*http.Response, error)
}

func (c *Client) SaveDataWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewSaveDataRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) SaveData(ctx context.Context, body SaveDataJSONRequestBody) (*http.Response, error) {
	req, err := NewSaveDataRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

// NewSaveDataRequest calls the generic SaveData builder with application/json body
func NewSaveDataRequest(server string, body SaveDataJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSaveDataRequestWithBody(server, "application/json", bodyReader)
}

// NewSaveDataRequestWithBody generates requests for SaveData with any type of body
func NewSaveDataRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/data")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SaveData request  with any body
	SaveDataWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*SaveDataResponse, error)

	SaveDataWithResponse(ctx context.Context, body SaveDataJSONRequestBody) (*SaveDataResponse, error)
}

type SaveDataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r SaveDataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SaveDataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SaveDataWithBodyWithResponse request with arbitrary body returning *SaveDataResponse
func (c *ClientWithResponses) SaveDataWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*SaveDataResponse, error) {
	rsp, err := c.SaveDataWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseSaveDataResponse(rsp)
}

func (c *ClientWithResponses) SaveDataWithResponse(ctx context.Context, body SaveDataJSONRequestBody) (*SaveDataResponse, error) {
	rsp, err := c.SaveData(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseSaveDataResponse(rsp)
}

// ParseSaveDataResponse parses an HTTP response from a SaveDataWithResponse call
func ParseSaveDataResponse(rsp *http.Response) (*SaveDataResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &SaveDataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Save new Data
	// (POST /data)
	SaveData(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SaveData converts echo context to params.
func (w *ServerInterfaceWrapper) SaveData(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SaveData(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/data", wrapper.SaveData)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xSy27bSBD8lUHvHmmR3l3sgTfZTgAdAjuxD3kgh/awTY0xr0w3ZROG/j2YoZTIFnXL",
	"hRz0q6q66wV0cDF48sLQvgDrNTkszysUzP+YQqQkhkoUP+evjJGgBeOFekqwrQC/nIh/nY/3J+b0J+b0",
	"J+YIuXiQ8YO7z4mcMWJzqOio9gXh/pG05M53KYV0LFCHjuahHDFjf5hkScb3OceCMvBc3wGTCfGISi4x",
	"/iHk7o5YJxPFBA8t3K0Nq+XNShlWA1OnJCjGDSnUYjZGRtWh4AIqsEaT58LNo8vT766vrqGCIVloYS0S",
	"27qW0IWFDg4OSC1X+1nLmxVUsKHEE/r5olk0uTRE8hgNtPBvCVUQUdZFbd3tXRJYjgXcZrKenhRqTZZS",
	"cCSUKtWPKbAOkRT6TuUbFiVQsBLm7lW369/dL9GPgVguQjdOZ/JCvkBijNbo0lQ/csbd+zi//k70AC38",
	"Vf82er1zeV1Gl/3P0D7ANYk6aCUNtM0BjsHz5JZ/mvM3bISepY4WzRsebyxzDJrxVEbu8s7/a5o/JnPy",
	"3QzkBXbq07TXYlQenMM0Hh5ut4Xns1+HOWMSMb4v+pfWhqer0aMz+n1I7gYTlhsztA9omapXJR8HSuNM",
	"zWWwlrTMZFb8YbBiLqc93EoidHmBU35bRDGlTen59vLa7zZotOvA0v7fNA1sv29/BgAA//9cbe5X8AQA",
	"AA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
